var MSG = {
  "title": "Kod",
  "blocks": "Bloklar",
  "runTooltip": "İş sahəsində bloklar tərəfindən müəyyən edilmiş proqramı işə salın.",
  "timeout": "Maksimum icra iterasiyaları aşdı.",
  "trashTooltip": "Bütün blokları atın.",
  "catLogic": "Məntiq",
  "catLoops": "Döngülər",
  "catMath": "Riyaziyyat",
  "catText": "Mətn",
  "catLists": "Siyahılar",
  "catColour": "Rəng",
  "catVariables": "Dəyişənlər",
  "catFunctions": "Funksiyalar",
  "listVariable": "siyahı",
  "textVariable": "mətn",
  "badXml": "XML təhlili zamanı xəta:\n%1\n\nDəyişikliklərdən imtina etmək üçün 'OK'-ı seçin və ya XML üzərində əlavə redaktə üçün 'Cancel'-ı seçin.",
  
  "c_Objects": "Obyektlər",
  "c_Blocks": "Bloklar",
  "c_Mobs": "Canlılar",
  "c_Items": "Əşyalar",
  "c_Time": "Zaman",
  "c_Movement": "Hərəkət",
  "c_Actions": "Fəaliyyətlər",
  "c_Drawing": "Çizim",
  "c_Events": "Hadisələr",
  "c_Status": "Vəziyyət",
  "c_Python": "Python",
  "c_ExamplesMenu": "Nümunələr ...",
  "c_Examples": "Nümunələr",
  "c_Algorithms": "Alqoritmlər",
  "t_saveTooltip": "Proqramı kompüterə yadda saxlayın",
  "t_readTooltip": "Kompüterdən proqramı yükləyin",
  "warn_entername": "MINECRAFT oyunçu adı sağ üst sahədə yoxdur",
  "info_deploySuccess": "Proqram Minecraft üçün hazırdır: %2",
  "info_deploySuccessWithWarning": "Proqram Minecraft üçün hazırdır, amma %2 onlayn deyil",
  "info_deployUnknownPlayer": "Mojang'ın %2 adlı bir oyunçu yoxdur",
  "infiniteLoopMessage": "Sonsuz döngü aşkarlandığı üçün proqram dayandırıldı"
}