var MSG = {
  "title": "Код",
  "blocks": "Блокове",
  "runTooltip": "Изпълни програмата, дефинирана от блоковете в работното пространство.",
  "timeout": "Превишен е максималният брой изпълнения.",
  "trashTooltip": "Премахни всички блокове.",
  "catLogic": "Логика",
  "catLoops": "Цикли",
  "catMath": "Математика",
  "catText": "Текст",
  "catLists": "Списъци",
  "catColour": "Цвят",
  "catVariables": "Променливи",
  "catFunctions": "Функции",
  "listVariable": "списък",
  "textVariable": "текст",
  "badXml": "Грешка при парсване на XML:\n%1\n\nИзберете 'ОК' за отказ от промените или 'Отмени' за допълнително редактиране на XML.",
  "c_Objects": "Обекти",
  "c_Blocks": "Блокове",
  "c_Mobs": "Мобове",
  "c_Items": "Предмети",
  "c_Time": "Време",
  "c_Movement": "Движение",
  "c_Actions": "Действия",
  "c_Drawing": "Рисуване",
  "c_Events": "Събития",
  "c_Status": "Статус",
  "c_Python": "Python",
  "c_ExamplesMenu": "Примери ...",
  "c_Examples": "Примери",
  "c_Algorithms": "Алгоритми",
  "t_saveTooltip": "Запази програмата на компютъра",
  "t_readTooltip": "Зареди програмата от компютъра",
  "warn_entername": "Името на играча в Minecraft липсва в горното дясно поле",
  "info_deploySuccess": "Програмата е готова в Minecraft за %2",
  "info_deploySuccessWithWarning": "Програмата е готова в Minecraft, но %2 не е онлайн",
  "info_deployUnknownPlayer": "Mojang няма играч на име %2",
  "infiniteLoopMessage": "Програмата е спряна, защото е открит безкраен цикъл"
}