var MSG = {
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
	  
	  c_Objects : "Objects",
	  c_Time : "Time",
	  c_Movement : "Movement",
	  c_Actions : "Actions",
	  c_Drawing : "Drawing",
	  c_Events : "Events",
	  c_Examples : "Examples",
	  c_Medusa : "Medusa",
	  c_Eiffel : "Eiffel Tower",
	  c_Train : "Train",
	  c_SpaceShip : "SpaceShip",  
	  c_Pumpkin : "Halloween",	  
	  c_Labirinth : "Labirinth",
	  c_Sphere : "Sphere",
	  c_Tower : "Tower",
	  c_Slide : "Slide",
	  c_Door : "Door",
	  c_Bridge : "Bridge",
	  c_Orientation : "Orientation",
	  c_Stadium : "Stadium",
	  c_Boat : "Motorboat",
	  c_Disco : "Disco",
	  c_Sail : "Sailing Boat",
	  c_Skull : "Skull",
	  c_Coca : "Coca Cola",
	  c_Bell : "Bell",
	  c_Regalo : "Present",
	  c_Renna : "Reindeer",
	  c_Pino : "Christmas Tree",
	  c_Empty : "",
	  c_Pool : "Swimming Pool",
	  c_Tennis : "Tennis Field",
	  c_Calendar : "Calendar 2018",
	  c_MountPolar : "Mountain",
	  c_StairSpiral : "Spiral Staircase",
	  c_Temple : "Temple",
	  c_Parkour : "Parkour",
	  c_Millennium : "Millennium",
	  c_Piano : "Piano",

	  c_Operators : "Op only",
	  t_saveTooltip : "Save the program on the computer",
	  t_readTooltip : "Load a program from the computer",
	  warn_entername :  "The MINECRAFT PLAYER NAME is missing in the top right field",
	  info_deploySuccess :  "The program is ready in Minecraft for %2",
	  info_deploySuccessWithWarning :  "The program is ready in Minecraft but %2 is not online"

};
