var MSG = {
  title: "Código",
  blocks: "Bloques",
  runTooltip: "Ejecuta el programa definido por los bloques en el espacio de trabajo.",
  timeout: "Se excedió el número máximo de iteraciones de ejecución.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Bucles",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  badXml: "Error al analizar XML:\n%1\n\nSelecciona 'OK' para abandonar tus cambios o 'Cancel' para seguir editando el XML.",
	  
  c_Objects : "Objetos",
  c_Blocks : "Bloques",
  c_Mobs : "Mobs",
  c_Items : "Objetos",
  c_Time : "Tiempo",
  c_Movement : "Movimiento",
  c_Actions : "Acciones",
  c_Drawing : "Dibujo",
  c_Events : "Eventos",
  c_Status : "Estado",
  c_Python : "Python",
  c_ExamplesMenu : "Ejemplos ...",
  c_Examples : "Ejemplos",
  c_Algorithms : "Algoritmos",
  t_saveTooltip : "Guardar el programa en la computadora",
  t_readTooltip : "Cargar un programa desde la computadora",
  warn_entername :  "El nombre de jugador de Minecraft falta en el campo superior derecho",
  info_deploySuccess :  "El programa está listo en Minecraft para %2",
  info_deploySuccessWithWarning :  "El programa está listo en Minecraft pero %2 no está en línea",
  info_deployUnknownPlayer :  "Mojang no tiene un jugador llamado %2",
  infiniteLoopMessage : "Programa detenido porque se detectó un bucle infinito"
};