var MSG = {
  "title": "Koodi",
  "blocks": "Lohkot",
  "runTooltip": "Suorita työtilassa olevien lohkojen määrittelemä ohjelma.",
  "timeout": "Suoritusten enimmäismäärä ylitetty.",
  "trashTooltip": "Poista kaikki lohkot.",
  "catLogic": "Logiikka",
  "catLoops": "Silmukat",
  "catMath": "Matematiikka",
  "catText": "Teksti",
  "catLists": "Listat",
  "catColour": "Väri",
  "catVariables": "Muuttujat",
  "catFunctions": "Funktiot",
  "listVariable": "lista",
  "textVariable": "teksti",
  "badXml": "Virhe XML:n jäsentämisessä:\n%1\n\nValitse 'OK' poistuaksesi muutoksista tai 'Peruuta' jatkaaksesi XML:n muokkaamista.",
  
  "c_Objects" : "Objektit",
  "c_Blocks" : "Lohkot",
  "c_Mobs" : "Mobit",
  "c_Items" : "Esineet",
  "c_Time" : "Aika",
  "c_Movement" : "Liike",
  "c_Actions" : "Toiminnot",
  "c_Drawing" : "Piirtäminen",
  "c_Events" : "Tapahtumat",
  "c_Status" : "Tila",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Esimerkit ...",
  "c_Examples" : "Esimerkit",
  "c_Algorithms" : "Algoritmit",
  "t_saveTooltip" : "Tallenna ohjelma tietokoneelle",
  "t_readTooltip" : "Lataa ohjelma tietokoneelta",
  "warn_entername" :  "Minecraft-pelaajan nimi puuttuu yläoikeassa kentässä",
  "info_deploySuccess" :  "Ohjelma on valmis Minecraftiin %2",
  "info_deploySuccessWithWarning" :  "Ohjelma on valmis Minecraftiin, mutta %2 ei ole verkossa",
  "info_deployUnknownPlayer" :  "Mojangilla ei ole pelaajaa nimeltä %2",
  "infiniteLoopMessage" : "Ohjelma pysäytetty, koska havaittiin ääretön silmukka"
}