var MSG = {
  title: "קוד",
  blocks: "קטעי קוד",
  linkTooltip: "שמירה וקישור לקטעי קוד.",
  runTooltip: "הרצת התכנית שהוגדרה על ידי קטעי הקוד שבמרחב העבודה.",
  badCode: "שגיאה בתכנית: %1",
  timeout: "חריגה ממספר פעולות חוזרות אפשריות.",
  trashTooltip: "השלך את כל קטעי הקוד.",
  catLogic: "לוגיקה",
  catLoops: "לולאות",
  catMath: "מתמטיקה",
  catText: "טקסט",
  catLists: "רשימות",
  catColour: "צבע",
  catVariables: "משתנים",
  catFunctions: "פונקציות",
  listVariable: "רשימה",
  textVariable: "טקסט",
  httpRequestError: "הבקשה נכשלה.",
  linkAlert: "ניתן לשתף את קטעי הקוד שלך באמצעות קישור זה:\n\n%1",
  hashError: "לצערנו, '%1' איננו מתאים לאף אחת מהתוכניות השמורות",
  xmlError: "נסיון הטעינה של הקובץ השמור שלך נכשל. האם ייתכן שהוא נוצר בגרסא שונה של בלוקלי?",
  badXml: "תקלה בפענוח XML:\n\n%1\n\nנא לבחור 'אישור' כדי לנטוש את השינויים שלך או 'ביטול' כדי להמשיך ולערוך את ה־XML.",
  
  c_Objects: "אובייקטים",
  c_Blocks: "בלוקים",
  c_Mobs: "מובים",
  c_Items: "פריטים",
  c_Time: "זמן",
  c_Movement: "תנועה",
  c_Actions: "פעולות",
  c_Drawing: "ציור",
  c_Events: "אירועים",
  c_Status: "סטטוס",
  c_Operators: "רק לאופרטורים",
  c_ExamplesMenu: "דוגמאות ...",
  c_Examples: "דוגמאות",
  c_Algorithms: "אלגוריתמים",
  t_saveTooltip: "שמור את התוכנית במחשב",
  t_readTooltip: "טען תוכנית מהמחשב",
  warn_entername: "שם השחקן ב-MINECRAFT חסר בשדה העליון הימני",
  info_deploySuccess: "התוכנית מוכנה ב-Minecraft עבור %2",
  info_deploySuccessWithWarning: "התוכנית מוכנה ב-Minecraft אך %2 לא מחובר",
  info_deployUnknownPlayer: "ל-Mojang אין שחקן בשם %2",
  infiniteLoopMessage: "התוכנית הופסקה כי זוהתה לולאה אינסופית"
	  
};
