var MSG = {
  title: "קוד",
  blocks: "קטעי קוד",
  linkTooltip: "שמירה וקישור לקטעי קוד.",
  runTooltip: "הרצת התכנית שהוגדרה על ידי קטעי הקוד שבמרחב העבודה.",
  badCode: "שגיאה בתכנית: %1",
  timeout: "חריגה ממספר פעולות חוזרות אפשריות.",
  trashTooltip: "השלך את כל קטעי הקוד.",
  catLogic: "לוגיקה",
  catLoops: "לולאות",
  catMath: "מתמטיקה",
  catText: "טקסט",
  catLists: "רשימות",
  catColour: "צבע",
  catVariables: "משתנים",
  catFunctions: "פונקציות",
  listVariable: "רשימה",
  textVariable: "טקסט",
  httpRequestError: "הבקשה נכשלה.",
  linkAlert: "ניתן לשתף את קטעי הקוד שלך באמצעות קישור זה:\n\n%1",
  hashError: "לצערנו, '%1' איננו מתאים לאף אחת מהתוכניות השמורות",
  xmlError: "נסיון הטעינה של הקובץ השמור שלך נכשל. האם ייתכן שהוא נוצר בגרסא שונה של בלוקלי?",
  badXml: "תקלה בפענוח XML:\n\n%1\n\nנא לבחור 'אישור' כדי לנטוש את השינויים שלך או 'ביטול' כדי להמשיך ולערוך את ה־XML.",
  
 	  c_Objects : "אובייקטים",
	  c_Time : "זמן",
	  c_Movement : "תנועה",
	  c_Actions : "פעולות",
	  c_Drawing : "ציור",
	  c_Events : "אירועים",
	  c_Operators : "מערכת",
	  c_ExamplesMenu : "דוגמאות ...",
	  c_Examples : "דוגמאות",
	  c_Algorithms : "אלגוריתמים",
  	  t_saveTooltip : "שמירה של הקוד במחשב",
	  t_readTooltip : "טעינת קוד מהמחשב",
	  warn_entername :  "שם השחקן לא מופיע בתיבה",
	  info_deploySuccess :  "התוכנה מקושרת במיינקראפט לשחקן %2",
	  info_deploySuccessWithWarning :  "התוכנה מקושרת במיינקראפט אבל השחקן %2 לא נמצא",
	  info_deployUnknownPlayer :  "התוכנה לא מצאה שחקן בשם %2",
	  infiniteLoopMessage : "התוכנה עצרה כי נמצאה לולאה אין סופית"
};
