var MSG = {
  "title": "Կոդ",
  "blocks": "Բլոկներ",
  "runTooltip": "Աշխատացրեք այն ծրագիրը, որը սահմանված է աշխատավայրի բլոկներով:",
  "timeout": "Կատարումների առավելագույն կրկնությունների թիվը գերազանցվեց.",
  "trashTooltip": "Հեռացրեք բոլոր բլոկները։",
  "catLogic": "Լոգիկա",
  "catLoops": "Կրկնություններ",
  "catMath": "Մաթեմատիկա",
  "catText": "Տեքստ",
  "catLists": "Ցանկեր",
  "catColour": "Գույն",
  "catVariables": "Փոփոխականներ",
  "catFunctions": "Ֆունկցիաներ",
  "listVariable": "ցանկ",
  "textVariable": "Տեքստ",
  "badXml": "XML-ը վերլուծելիս սխալ:\n%1\n\nԸնտրեք 'OK', որպեսզի հրաժարվեք ձեր փոփոխություններից կամ 'Cancel', որպեսզի XML-ը դեռ խմբագրեք:",
  "c_Objects": "Օբյեկտներ",
  "c_Blocks": "Բլոկներ",
  "c_Mobs": "Մոբեր",
  "c_Items": "Առարկաներ",
  "c_Time": "Ժամանակ",
  "c_Movement": "Շարժում",
  "c_Actions": "Գործողություններ",
  "c_Drawing": "Նկարում",
  "c_Events": "Իրադարձություններ",
  "c_Status": "Վիճակ",
  "c_Python": "Python",
  "c_ExamplesMenu": "Օրինակներ ...",
  "c_Examples": "Օրինակներ",
  "c_Algorithms": "Ալգորիթմներ",
  "t_saveTooltip": "Ծրագիրը պահպանել համակարգչի վրա",
  "t_readTooltip": "Ծրագիր բեռնել համակարգչից",
  "warn_entername": "Minecraft խաղացողի անունը բացակայում է վերին աջ դաշտում",
  "info_deploySuccess": "Ծրագիրը Minecraft-ում պատրաստ է, עבור %2",
  "info_deploySuccessWithWarning": "Ծրագիրը Minecraft-ում պատրաստ է, բայց %2-ը առցանց չէ",
  "info_deployUnknownPlayer": "Mojang-ը չունի %2 անունով խաղացող",
  "infiniteLoopMessage": "Ծրագիրը կանգնեց անվերջ ցիկլի հայտնաբրման պատճառով"
}