var MSG = {
  "title": "Kóði",
  "blocks": "Blokkir",
  "runTooltip": "Keyra forritið sem skilgreint er með blokkum í vinnusvæðinu.",
  "timeout": "Náðist hámarks fjölda keyrslna.",
  "trashTooltip": "Henda öllum blokkum.",
  "catLogic": "Rökfræði",
  "catLoops": "Lykkjur",
  "catMath": "Stærðfræði",
  "catText": "Texti",
  "catLists": "Listar",
  "catColour": "Litur",
  "catVariables": "Breytilar",
  "catFunctions": "Föll",
  "listVariable": "listi",
  "textVariable": "texti",
  "badXml": "Villa við gagnagreiningu XML:\n%1\n\nVeldu 'OK' til að yfirgefa breytingarnar eða 'Cancel' til frekara breyta XML.",
  
  "c_Objects": "Hlutir",
  "c_Blocks": "Blokkir",
  "c_Mobs": "Verur",
  "c_Items": "Hlutir",
  "c_Time": "Tími",
  "c_Movement": "Hreyfing",
  "c_Actions": "Aðgerðir",
  "c_Drawing": "Teikning",
  "c_Events": "Atburðir",
  "c_Status": "Staða",
  "c_Python": "Python",
  "c_ExamplesMenu": "Dæmi ...",
  "c_Examples": "Dæmi",
  "c_Algorithms": "Algoritmar",
  "t_saveTooltip": "Vista forritið á tölvunni",
  "t_readTooltip": "Hlaða forriti frá tölvunni",
  "warn_entername": "Minecraft leikmannanafnið vantar í hægra efri reitinn",
  "info_deploySuccess": "Forritið er tilbúið í Minecraft fyrir %2",
  "info_deploySuccessWithWarning": "Forritið er tilbúið í Minecraft en %2 er ekki á netinu",
  "info_deployUnknownPlayer": "Mojang hefur ekki leikmann sem kallast %2",
  "infiniteLoopMessage": "Forrit stoppaði vegna óendanlegrar lykkju"
}