var MSG = {
  title: "Codice",
  blocks: "Blocchi",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Esegui il programma definito dai blocchi nell'area di lavoro.",
  badCode: "Errore programma:\n%1",
  timeout: "È stato superato il numero massimo consentito di interazioni eseguite.",
  trashTooltip: "Elimina tutti i blocchi.",
  catLogic: "Logica",
  catLoops: "Cicli",
  catMath: "Matematica",
  catText: "Testo",
  catLists: "Elenchi",
  catColour: "Colore",
  catVariables: "Variabili",
  catFunctions: "Funzioni",
  listVariable: "elenco",
  textVariable: "testo",
  httpRequestError: "La richiesta non è stata soddisfatta.",
  linkAlert: "Condividi i tuoi blocchi con questo collegamento:\n\n%1",
  hashError: "Mi spiace, '%1' non corrisponde ad alcun programma salvato.",
  xmlError: "Non è stato possibile caricare il documento.  Forse è stato creato con una versione diversa di Blockly?",
  badXml: "Errore durante l'analisi XML:\n%1\n\nSeleziona 'OK' per abbandonare le modifiche o 'Annulla' per continuare a modificare l'XML.",

	  c_Objects : "Oggetti",
	  c_Time : "Tempo",
	  c_Movement : "Movimento",
	  c_Actions : "Azioni",
	  c_Drawing : "Disegno",
	  c_Events : "Eventi",
	  c_Examples : "Esempi",
	  c_Medusa : "Medusa",
	  c_Eiffel : "Torre Eiffel",
	  c_Train : "Treno",
	  c_SpaceShip : "Navicella Spaziale",
	  c_Pumpkin : "Halloween",
	  c_Labirinth : "Labirinto",
	  c_Sphere : "Sfera",
	  c_Tower : "Torre",
	  c_Slide : "Scivolo",
	  c_Door : "Porta",
	  c_Bridge : "Ponte",
	  c_Orientation : "Orientazione",
	  c_Stadium : "Stadio",
	  c_Boat : "Motoscafo",
	  c_Disco : "Disco",
	  c_Sail : "Veliero",
	  c_Skull : "Teschio",
	  c_Coca : "Coca Cola",
	  c_Bell : "Campana",
	  c_Regalo : "Regalo",
	  c_Renna : "Renna",
	  c_Pino : "Albero di natale",
	  c_Empty : "",
	  c_Pool : "Piscina",
	  c_Tennis : "Campo da Tennis",
	  c_Calendar : "Calendario 2018",
	  c_MountPolar : "Montagna",
	  c_StairSpiral : "Scala a Spirale",
	  c_Temple : "Tempio",
	  c_Parkour : "Parkour",
	  c_Millennium : "Millennium",
	  c_Piano : "Pianoforte",
	  c_Operators : "Solo Op",
	  t_saveTooltip : "Salva il programma sul computer",
	  t_readTooltip : "Carica un programma dal computer",
	  warn_entername :  "Manca il NOME DEL GIOCATORE in Minecraft nel campo in alto a destra",
	  info_deploySuccess :  "Il programma è pronto in Minecraft per %2",
	  info_deploySuccessWithWarning :  "Il programma è pronto in Minecraft ma il giocatore %2 non è online"



};
