var MSG = {
  "title": "ಕೋಡ್",
  "blocks": "ಬ್ಲಾಕ್‌ಗಳು",
  "runTooltip": "ವರ್ಕ್‌ಸ್ಪೇಸ್‌ನಲ್ಲಿನ ಬ್ಲಾಕ್‌ಗಳಿಂದ ನಿರ್ಧಾರಿತ ಪ್ರೋಗ್ರಾಮ್ ಅನ್ನು ಚಾಲನೆ ಮಾಡಿ.",
  "timeout": "ಗರಿಷ್ಠ ನಿರ್ವಹಣಾ ಪುನರಾವೃತಿಗಳು ದಾಟಿವೆ.",
  "trashTooltip": "ಎಲ್ಲಾ ಬ್ಲಾಕ್‌ಗಳನ್ನು ತ್ಯಜಿಸಿ.",
  "catLogic": "ತಾರ್ಕಿಕ",
  "catLoops": "ಲೂಪ್ಸ್",
  "catMath": "ಗಣಿತ",
  "catText": "ಪಠ್ಯ",
  "catLists": "ಪಟ್ಟಿಗಳು",
  "catColour": "ಬಣ್ಣ",
  "catVariables": "ಚರಗಳು",
  "catFunctions": "ಕ್ರಿಯೆಗಳು",
  "listVariable": "ಪಟ್ಟಿ",
  "textVariable": "ಪಠ್ಯ",
  "badXml": "XML ಅನ್ನು ಪಾರ್ಸಿಂಗ್ ಮಾಡುವಾಗ ದೋಷ:\n%1\n\nನಿಮ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ತ್ಯಜಿಸಿ 'OK' ಆಯ್ಕೆ ಮಾಡಿ ಅಥವಾ XML ಅನ್ನು ಮುಂದುವರೆದು ಸಂಪಾದಿಸಲು 'Cancel' ಆಯ್ಕೆ ಮಾಡಿ.",
  "c_Objects": "ವಸ್ತುಗಳು",
  "c_Blocks": "ಬ್ಲಾಕ್‌ಗಳು",
  "c_Mobs": "ಮೊಬ್‌ಗಳು",
  "c_Items": "ಐಟಂಗಳು",
  "c_Time": "ಕಾಲ",
  "c_Movement": "ಚಲನೆ",
  "c_Actions": "ಕ್ರಿಯೆಗಳು",
  "c_Drawing": "ಚಿತ್ರಣ",
  "c_Events": "ಘಟನೆಗಳು",
  "c_Status": "ಸ್ಥಿತಿ",
  "c_Python": "ಪೈಥನ್",
  "c_ExamplesMenu": "ಉದಾಹರಣೆಗಳು ...",
  "c_Examples": "ಉದಾಹರಣೆಗಳು",
  "c_Algorithms": "ಅಲ್ಗೋರಿದಮ್‌ಗಳು",
  "t_saveTooltip": "ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಪ್ರೋಗ್ರಾಂ ಉಳಿಸಿ",
  "t_readTooltip": "ಕಂಪ್ಯೂಟರ್‌ನಿಂದ ಪ್ರೋಗ್ರಾಂ ಲೋಡ್ ಮಾಡಿ",
  "warn_entername": "Minecraft ಆಟಗಾರನ ಹೆಸರನ್ನು ಮೇಲ್ಭಾಗದ ಬಲದ ಫೀಲ್ಡಿನಲ್ಲಿ ಕಾಣಿಸಲಾಗಿಲ್ಲ",
  "info_deploySuccess": "Minecraft ನಲ್ಲಿ %2 ಗಾಗಿ ಪ್ರೋಗ್ರಾಂ ಸಿದ್ಧವಾಗಿದೆ",
  "info_deploySuccessWithWarning": "Minecraft ನಲ್ಲಿ ಪ್ರೋಗ್ರಾಂ ಸಿದ್ಧವಾಗಿದೆ ಆದರೆ %2 ಆನ್‌ಲೈನ್‌ ಅಲ್ಲ",
  "info_deployUnknownPlayer": "Mojangನಲ್ಲಿ %2 ಎಂಬ ಆಟಗಾರ ಇಲ್ಲ",
  "infiniteLoopMessage": "ಪ್ರೋಗ್ರಾಂವು ಅನಂತ ಲೂಪ್ ಪತ್ತೆಯಾಗಿರುವದರಿಂದ ನಿಲ್ಲಿಸಲಾಗಿದೆ"
}