var MSG = {
  "title": "ລະຫັດ",
  "blocks": "ບລອກ",
  "runTooltip": "ເຮັດວຽກງານຂອງລາຍການທີ່ກຳນົດໂດຍບລອກໃນພື້ນການງານ.",
  "timeout": "ການດຳເນີນການທະກຳນອງບໍ່ສາມາດກວດສອບການດຳເນີນ.",
  "trashTooltip": "ຍົກລອກບລອກທັງໝົດ.",
  "catLogic": "ບົດຄວາມ",
  "catLoops": "ວົກການ",
  "catMath": "ຄະນະ",
  "catText": "ຂໍ້ຄວາມ",
  "catLists": "ລາຍການ",
  "catColour": "ສີ",
  "catVariables": "ຕົວແປກ",
  "catFunctions": "ຟັງຊັ່ນ",
  "listVariable": "ລາຍການ",
  "textVariable": "ຂໍ້ຄວາມ",
  "badXml": "ຂໍ້ຜິດ XML:\n%1\n\nເລືອກ 'OK' ເພື່ອປອກການດັດປຽນຂອງທ່ານຫຼື 'Cancel' ເພື່ອແກ້ໄຂ XML ຕໍ່.",
  "c_Objects": "ວັດ",
  "c_Blocks": "ບລອກ",
  "c_Mobs": "ມອບ",
  "c_Items": "ອຸປະກອນ",
  "c_Time": "ເວລາ",
  "c_Movement": "ການຍ່າງ",
  "c_Actions": "ການກະທຳ",
  "c_Drawing": "ການສ້າງຮູບ",
  "c_Events": "ເຫດການ",
  "c_Status": "ສະຖານະ",
  "c_Python": "Python",
  "c_ExamplesMenu": "Examples ...",
  "c_Examples": "ຕົວຢ່າງ",
  "c_Algorithms": "ອິລະທິມ",
  "t_saveTooltip": "ບັນທຶກໂປຣກຣຳໃນຄອມພິວເຕີ",
  "t_readTooltip": "ເຄື່ອນໄຫວໂປຣກຣຳຈາກຄອມພິວເຕີ",
  "warn_entername": "The MINECRAFT PLAYER NAME is missing in the top right field",
  "info_deploySuccess": "The program is ready in Minecraft for %2",
  "info_deploySuccessWithWarning": "The program is ready in Minecraft but %2 is not online",
  "info_deployUnknownPlayer": "Mojang doesn't have a player called %2",
  "infiniteLoopMessage": "Program stopped because an infinite loop was detected"
}