var MSG = {
  "title": "Kodas",
  "blocks": "Blokai",
  "runTooltip": "Vykdykite programą, kurią apibrėžia blokai darbo erdvėje.",
  "timeout": "Viršytas maksimalus vykdymo kartų skaičius.",
  "trashTooltip": "Išmesti visus blokus.",
  "catLogic": "Logika",
  "catLoops": "Ciklai",
  "catMath": "Matematika",
  "catText": "Tekstas",
  "catLists": "Sąrašai",
  "catColour": "Spalva",
  "catVariables": "Kintamieji",
  "catFunctions": "Funkcijos",
  "listVariable": "sąrašas",
  "textVariable": "tekstas",
  "badXml": "Klaida analizuojant XML:\n%1\n\nPasirinkite 'Gerai' norėdami atsisakyti pakeitimų arba 'Atšaukti' tęsti XML redagavimą.",
  
  "c_Objects": "Objektai",
  "c_Blocks": "Blokai",
  "c_Mobs": "Mobai",
  "c_Items": "Daiktai",
  "c_Time": "Laikas",
  "c_Movement": "Judėjimas",
  "c_Actions": "Veiksmai",
  "c_Drawing": "Piešimas",
  "c_Events": "Įvykiai",
  "c_Status": "Būsena",
  "c_Python": "Python",
  "c_ExamplesMenu": "Pavyzdžiai ...",
  "c_Examples": "Pavyzdžiai",
  "c_Algorithms": "Algoritmai",
  "t_saveTooltip": "Išsaugoti programą kompiuteryje",
  "t_readTooltip": "Įkelti programą iš kompiuterio",
  "warn_entername": "MINECRAFT žaidėjo vardas trūksta dešiniajame viršutiniame lauke",
  "info_deploySuccess": "Programa paruošta Minecraft %2",
  "info_deploySuccessWithWarning": "Programa paruošta Minecraft, bet %2 nėra prisijungęs",
  "info_deployUnknownPlayer": "Mojang neturi žaidėjo, kurio vardas yra %2",
  "infiniteLoopMessage": "Programa sustabdyta, nes buvo aptikta begalinė kilpa"
}