var MSG = {
  title: "Kode",
  blocks: "Blokker",
  runTooltip: "Kjør programmet definert av blokkene i arbeidsområdet.",
  timeout: "Maks antall kjøringer overskredet.",
  trashTooltip: "Kast alle blokkene.",
  catLogic: "Logikk",
  catLoops: "Løkker",
  catMath: "Matematikk",
  catText: "Tekst",
  catLists: "Lister",
  catColour: "Farge",
  catVariables: "Variabler",
  catFunctions: "Funksjoner",
  listVariable: "liste",
  textVariable: "tekst",
  badXml: "Feil ved parsing av XML:\n%1\n\nVelg 'OK' for å forkaste endringene dine eller 'Avbryt' for å fortsette å redigere XML-en.",
	  
  c_Objects : "Objekter",
  c_Blocks : "Blokker",
  c_Mobs : "Monstre",
  c_Items : "Gjenstander",
  c_Time : "Tid",
  c_Movement : "Bevegelse",
  c_Actions : "Handlinger",
  c_Drawing : "Tegning",
  c_Events : "Hendelser",
  c_Status : "Status",
  c_Python : "Python",
  c_ExamplesMenu : "Eksempler ...",
  c_Examples : "Eksempler",
  c_Algorithms : "Algoritmer",
  t_saveTooltip : "Lagre programmet på datamaskinen",
  t_readTooltip : "Last inn et program fra datamaskinen",
  warn_entername :  "Minecraft-spillernavn mangler i feltet øverst til høyre",
  info_deploySuccess :  "Programmet er klart i Minecraft for %2",
  info_deploySuccessWithWarning :  "Programmet er klart i Minecraft, men %2 er ikke online",
  info_deployUnknownPlayer :  "Mojang har ikke en spiller som heter %2",
  infiniteLoopMessage : "Programmet stoppet fordi en uendelig løkke ble oppdaget"
};