var MSG = {
  "title": "Kod",
  "blocks": "Bloki",
  "runTooltip": "Uruchom program zdefiniowany przez bloki w środowisku roboczym.",
  "timeout": "Przekroczono maksymalną liczbę iteracji wykonania.",
  "trashTooltip": "Usuń wszystkie bloki.",
  "catLogic": "Logika",
  "catLoops": "Pętle",
  "catMath": "Matematyka",
  "catText": "Tekst",
  "catLists": "Listy",
  "catColour": "Kolor",
  "catVariables": "Zmienne",
  "catFunctions": "Funkcje",
  "listVariable": "lista",
  "textVariable": "tekst",
  "badXml": "Błąd podczas analizy XML:\n%1\n\nWybierz 'OK', aby porzucić wprowadzone zmiany lub 'Anuluj', aby kontynuować edycję XML.",
  "c_Objects": "Obiekty",
  "c_Blocks": "Bloki",
  "c_Mobs": "Moby",
  "c_Items": "Przedmioty",
  "c_Time": "Czas",
  "c_Movement": "Ruch",
  "c_Actions": "Działania",
  "c_Drawing": "Rysowanie",
  "c_Events": "Zdarzenia",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Przykłady ...",
  "c_Examples": "Przykłady",
  "c_Algorithms": "Algorytmy",
  "t_saveTooltip": "Zapisz program na komputerze",
  "t_readTooltip": "Wczytaj program z komputera",
  "warn_entername": "Brak nazwy gracza Minecraft w prawym górnym polu",
  "info_deploySuccess": "Program jest gotowy w Minecraft dla %2",
  "info_deploySuccessWithWarning": "Program jest gotowy w Minecraft, ale %2 nie jest online",
  "info_deployUnknownPlayer": "Mojang nie ma gracza o nazwie %2",
  "infiniteLoopMessage": "Program zatrzymany, wykryto nieskończoną pętlę"
}