var MSG = {
  "title": "Cod",
  "blocks": "Blocuri",
  "runTooltip": "Rulează programul definit de blocuri în spațiul de lucru.",
  "timeout": "Numărul maxim de iterații de execuție a fost atins.",
  "trashTooltip": "Aruncă toate blocurile.",
  "catLogic": "Logică",
  "catLoops": "Bucle",
  "catMath": "Matematică",
  "catText": "Text",
  "catLists": "Liste",
  "catColour": "Culoare",
  "catVariables": "Variabile",
  "catFunctions": "Funcții",
  "listVariable": "listă",
  "textVariable": "text",
  "badXml": "Eroare în analizarea XML:\n%1\n\nSelectați 'OK' pentru a renunța la modificările dvs. sau 'Cancel' pentru a edita în continuare XML-ul.",
  
  "c_Objects": "Obiecte",
  "c_Blocks": "Blocuri",
  "c_Mobs": "Creaturi",
  "c_Items": "Obiecte",
  "c_Time": "Timp",
  "c_Movement": "Mișcare",
  "c_Actions": "Acțiuni",
  "c_Drawing": "Desen",
  "c_Events": "Evenimente",
  "c_Status": "Stare",
  "c_Python": "Python",
  "c_ExamplesMenu": "Exemple ...",
  "c_Examples": "Exemple",
  "c_Algorithms": "Algoritmi",
  "t_saveTooltip": "Salvează programul pe calculator",
  "t_readTooltip": "Încarcă un program de pe calculator",
  "warn_entername": "Numele jucătorului Minecraft lipsește în câmpul din dreapta sus",
  "info_deploySuccess": "Programul este gata în Minecraft pentru %2",
  "info_deploySuccessWithWarning": "Programul este gata în Minecraft, dar %2 nu este online",
  "info_deployUnknownPlayer": "Mojang nu are un jucător numit %2",
  "infiniteLoopMessage": "Programul s-a oprit deoarece a fost detectat un ciclu infinit"
}