var MSG = {
  title: "Kód",
  blocks: "Bloky",
  runTooltip: "Spustí program definovaný blokmi v pracovnom priestore.",
  timeout: "Prekročený maximálny počet vykonaných iterácií.",
  trashTooltip: "Vymazať všetky bloky.",
  catLogic: "Logika",
  catLoops: "Slučky",
  catMath: "Matematika",
  catText: "Text",
  catLists: "Zoznamy",
  catColour: "Farba",
  catVariables: "Premenné",
  catFunctions: "Funkcie",
  listVariable: "zoznam",
  textVariable: "reťazec",
  badXml: "Chyba pri parsovaní XML:\n%1\n\nVyberte 'OK' na opustenie zmien alebo 'Zrušiť' pre ďalšiu úpravu XML.",
  
  c_Objects : "Objekty",
  c_Blocks : "Bloky",
  c_Mobs : "Monštrá",
  c_Items : "Predmety",
  c_Time : "Čas",
  c_Movement : "Pohyb",
  c_Actions : "Akcie",
  c_Drawing : "Kreslenie",
  c_Events : "Udalosti",
  c_Status : "Stav",
  c_Python : "Python",
  c_ExamplesMenu : "Príklady ...",
  c_Examples : "Príklady",
  c_Algorithms : "Algoritmy",
  t_saveTooltip : "Uložiť program do počítača",
  t_readTooltip : "Načítať program zo počítača",
  warn_entername :  "MENO HRÁČA MINECRAFTU chýba v pravom hornom poli",
  info_deploySuccess :  "Program je pripravený v Minecraft pre %2",
  info_deploySuccessWithWarning :  "Program je pripravený v Minecraft, ale %2 nie je online",
  info_deployUnknownPlayer :  "Mojang nemá hráča s menom %2",
  infiniteLoopMessage : "Program bol zastavený, pretože bol zistený nekonečný cyklus"
};