var MSG = {
  "title": "Kod",
  "blocks": "Block",
  "runTooltip": "Kör programmet som definieras av blocken i arbetsytan.",
  "timeout": "Det maximala antalet exekveringsiterationer har överskridits.",
  "trashTooltip": "Radera alla block.",
  "catLogic": "Logik",
  "catLoops": "Loopar",
  "catMath": "Matematik",
  "catText": "Text",
  "catLists": "Listor",
  "catColour": "Färg",
  "catVariables": "Variabler",
  "catFunctions": "Funktioner",
  "listVariable": "lista",
  "textVariable": "text",
  "badXml": "Fel vid tolkning av XML:\n%1\n\nVälj 'OK' för att överge dina ändringar eller 'Avbryt' för att fortsätta redigera XML.",
  
  "c_Objects": "Objekt",
  "c_Blocks": "Block",
  "c_Mobs": "Mobs",
  "c_Items": "Föremål",
  "c_Time": "Tid",
  "c_Movement": "Rörelse",
  "c_Actions": "Åtgärder",
  "c_Drawing": "Ritning",
  "c_Events": "Händelser",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Exempel ...",
  "c_Examples": "Exempel",
  "c_Algorithms": "Algoritmer",
  "t_saveTooltip": "Spara programmet på datorn",
  "t_readTooltip": "Läs in ett program från datorn",
  "warn_entername": "MINECRAFT-spelarnamnet saknas i fältet högst upp till höger",
  "info_deploySuccess": "Programmet är redo i Minecraft för %2",
  "info_deploySuccessWithWarning": "Programmet är klart i Minecraft men %2 är inte online",
  "info_deployUnknownPlayer": "Mojang har inte någon spelare som heter %2",
  "infiniteLoopMessage": "Programmet stoppades eftersom en oändlig loop upptäcktes"
}