var MSG = {
  "title": "Kod",
  "blocks": "Bloklar",
  "runTooltip": "Çalışma alanındaki bloklar tarafından tanımlanan programı çalıştır.",
  "timeout": "En fazla yürütme yinelemesi aşıldı.",
  "trashTooltip": "Tüm blokları kaldır.",
  "catLogic": "Mantık",
  "catLoops": "Döngüler",
  "catMath": "Matematik",
  "catText": "Metin",
  "catLists": "Listeler",
  "catColour": "Renk",
  "catVariables": "Değişkenler",
  "catFunctions": "Fonksiyonlar",
  "listVariable": "liste",
  "textVariable": "metin",
  "badXml": "XML ayrıştırılırken hata:\n%1\n\nDeğişiklikleri geri almak için 'Tamam'ı seçin veya XML'yi daha fazla düzenlemek için 'İptal' tuşuna basın.",
  
  "c_Objects" : "Nesneler",
  "c_Blocks" : "Bloklar",
  "c_Mobs" : "MOB'lar",
  "c_Items" : "Eşyalar",
  "c_Time" : "Zaman",
  "c_Movement" : "Hareket",
  "c_Actions" : "Eylemler",
  "c_Drawing" : "Çizim",
  "c_Events" : "Olaylar",
  "c_Status" : "Durum",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Örnekler ...",
  "c_Examples" : "Örnekler",
  "c_Algorithms" : "Algoritmalar",
  "t_saveTooltip" : "Programı bilgisayara kaydet.",
  "t_readTooltip" : "Bilgisayardan bir program yükle.",
  "warn_entername" :  "MINECRAFT OYUNCU ADI sağ üst alanda eksik",
  "info_deploySuccess" :  "Minecraft'ta %2 için program hazır.",
  "info_deploySuccessWithWarning" :  "Minecraft'ta program hazır fakat %2 çevrimiçi değil.",
  "info_deployUnknownPlayer" :  "Mojang'da %2 adlı bir oyuncu bulunmuyor.",
  "infiniteLoopMessage" : "Sonsuz döngü tespit edildiği için program durduruldu"
}