var MSG = {
  "title": "Код",
  "blocks": "Блоки",
  "runTooltip": "Запустити програму, визначену за допомогою блоків у робочому просторі.",
  "timeout": "Перевищено максимальну кількість ітерацій виконання.",
  "trashTooltip": "Видалити всі блоки.",
  "catLogic": "Логіка",
  "catLoops": "Цикли",
  "catMath": "Математика",
  "catText": "Текст",
  "catLists": "Списки",
  "catColour": "Колір",
  "catVariables": "Змінні",
  "catFunctions": "Функції",
  "listVariable": "список",
  "textVariable": "текст",
  "badXml": "Помилка розбору XML:\n%1\n\nВиберіть 'OK' для скасування змін або 'Cancel' для подальшого редагування XML.",
  
  "c_Objects": "Об'єкти",
  "c_Blocks": "Блоки",
  "c_Mobs": "Моби",
  "c_Items": "Предмети",
  "c_Time": "Час",
  "c_Movement": "Переміщення",
  "c_Actions": "Дії",
  "c_Drawing": "Малювання",
  "c_Events": "Події",
  "c_Status": "Статус",
  "c_Python": "Python",
  "c_ExamplesMenu": "Приклади ...",
  "c_Examples": "Приклади",
  "c_Algorithms": "Алгоритми",
  "t_saveTooltip": "Зберегти програму на комп’ютері",
  "t_readTooltip": "Завантажити програму з комп’ютера",
  "warn_entername": "Ім'я гравця Minecraft відсутнє у верхньому правому полі",
  "info_deploySuccess": "Програма готова в Minecraft для %2",
  "info_deploySuccessWithWarning": "Програма готова в Minecraft, але %2 не онлайн",
  "info_deployUnknownPlayer": "У Mojang немає гравця з ім’ям %2",
  "infiniteLoopMessage": "Програма зупинена через виявлення нескінченного циклу"
}