var MSG = {
  "title": "Koodu",
  "blocks": "Awọn bulọọki",
  "runTooltip": "Ṣe eto tí a ṣe ìtumọ̀ nípa àwọn bulọọki ní agbègbè iṣẹ́.",
  "timeout": "Ọpọ ìyípadà ìṣiṣẹ́ ti kọja.",
  "trashTooltip": "Yọ gbogbo awọn bulọọki.",
  "catLogic": "Òye",
  "catLoops": "Ìyípadà",
  "catMath": "Ìṣirò",
  "catText": "Ọ̀rọ̀",
  "catLists": "Àwọn Akojọ",
  "catColour": "Àwọ̀",
  "catVariables": "Àwọn Iyipada",
  "catFunctions": "Àwọn Iṣẹ",
  "listVariable": "Àkójọpọ̀",
  "textVariable": "Ọ̀rọ̀",
  "badXml": "Àṣìṣe ní ìtumọ XML:\n%1\n\nYan 'OK' láti fi àwọn ìyípadà rẹ silẹ tàbí 'Cancel' láti tún ṣatúnṣe XML.",
  
  "c_Objects": "Àwọn nkan",
  "c_Blocks": "Àwọn bulọọki",
  "c_Mobs": "Àwọn Mọ̀bù",
  "c_Items": "Àwọn Nkan",
  "c_Time": "Àkókò",
  "c_Movement": "Gbigbé",
  "c_Actions": "Ìṣe",
  "c_Drawing": "Ìyaworan",
  "c_Events": "Àwọn iṣẹlẹ",
  "c_Status": "Ìpò",
  "c_Python": "Python",
  "c_ExamplesMenu": "Àpẹẹrẹ ...",
  "c_Examples": "Àpẹẹrẹ",
  "c_Algorithms": "Algoritimu",
  "t_saveTooltip": "Fipamọ eto naa sori kọmputa",
  "t_readTooltip": "Gba eto kan lati kọmputa",
  "warn_entername": "Orúkọ òṣere Minecraft ti o wa ní apá òtún loke kò sí",
  "info_deploySuccess": "Eto naa ti ṣetan ninu Minecraft fun %2",
  "info_deploySuccessWithWarning": "Eto naa ti ṣetan ninu Minecraft ṣugbọn %2 kò sí lori ayelujara",
  "info_deployUnknownPlayer": "Mojang kò ní oṣere tí a pe ní %2",
  "infiniteLoopMessage": "Eto duro nitori a ti ri ìlòpo ailopin"
}