var MSG = {
  "title": "程式碼",
  "blocks": "積木",
  "runTooltip": "執行工作區中由區塊定義的程式。",
  "timeout": "已達到最大執行迭代次數。",
  "trashTooltip": "放棄所有區塊。",
  "catLogic": "邏輯",
  "catLoops": "迴圈",
  "catMath": "數學",
  "catText": "文字",
  "catLists": "清單",
  "catColour": "顏色",
  "catVariables": "變數",
  "catFunctions": "函數",
  "listVariable": "清單",
  "textVariable": "文字",
  "badXml": "解析 XML 時發生錯誤:\n%1\n\n選擇「確定」以放棄變更或「取消」以繼續編輯 XML。",
	  
  "c_Objects" : "物件",
  "c_Blocks" : "區塊",
  "c_Mobs" : "生物",
  "c_Items" : "物品",
  "c_Time" : "時間",
  "c_Movement" : "移動",
  "c_Actions" : "動作",
  "c_Drawing" : "繪畫",
  "c_Events" : "事件",
  "c_Status" : "狀態",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "範例 ...",
  "c_Examples" : "範例",
  "c_Algorithms" : "演算法",
  "t_saveTooltip" : "將程式儲存到電腦上",
  "t_readTooltip" : "從電腦載入程式",
  "warn_entername" :  "右上方欄位中缺少 Minecraft 玩家名稱",
  "info_deploySuccess" :  "該程式在 Minecraft 中就緒，適用於 %2",
  "info_deploySuccessWithWarning" :  "該程式已就緒於 Minecraft，但 %2 尚未上線",
  "info_deployUnknownPlayer" :  "Mojang 沒有名為 %2 的玩家",
  "infiniteLoopMessage" : "偵測到無限迴圈，程式已停止"
}