var MSG = {
  title: "الكود",
  blocks: "كتل",
  runTooltip: "تشغيل البرنامج المحدد بواسطة الكتل في مساحة العمل.",
  timeout: "تم تجاوز الحد الأقصى لتكرارات التنفيذ.",
  trashTooltip: "إزالة جميع الكتل.",
  catLogic: "المنطق",
  catLoops: "الحلقات",
  catMath: "الرياضيات",
  catText: "النص",
  catLists: "القوائم",
  catColour: "اللون",
  catVariables: "المتغيرات",
  catFunctions: "الدوال",
  listVariable: "قائمة",
  textVariable: "نص",
  badXml: "خطأ في تحليل XML:\n%1\n\nاختر 'موافق' لترك تغييراتك أو 'إلغاء' لاستكمال تحرير XML.",
	  
  c_Objects : "الكائنات",
  c_Blocks : "كتل",
  c_Mobs : "المخلوقات",
  c_Items : "العناصر",
  c_Time : "الوقت",
  c_Movement : "الحركة",
  c_Actions : "الإجراءات",
  c_Drawing : "الرسم",
  c_Events : "الأحداث",
  c_Status : "الحالة",
  c_Python : "بايثون",
  c_ExamplesMenu : "أمثلة ...",
  c_Examples : "أمثلة",
  c_Algorithms : "الخوارزميات",
  t_saveTooltip : "احفظ البرنامج على الكمبيوتر",
  t_readTooltip : "تحميل برنامج من الكمبيوتر",
  warn_entername :  "اسم لاعب ماين كرافت مفقود في الحقل العلوي الأيمن",
  info_deploySuccess :  "البرنامج جاهز في ماين كرافت لـ %2",
  info_deploySuccessWithWarning :  "البرنامج جاهز في ماين كرافت، ولكن %2 غير متصل",
  info_deployUnknownPlayer :  "لا يوجد لاعب باسم %2 في Mojang",
  infiniteLoopMessage : "تم إيقاف البرنامج بسبب اكتشاف حلقة لا نهائية"

};