var MSG = {
  "title": "Kód",
  "blocks": "Bloky",
  "runTooltip": "Spusťte program definovaný bloky ve pracovním prostoru.",
  "timeout": "Překročen maximální počet provedených iterací.",
  "trashTooltip": "Odeberte všechny bloky.",
  "catLogic": "Logika",
  "catLoops": "Smyčky",
  "catMath": "Matematika",
  "catText": "Text",
  "catLists": "Seznamy",
  "catColour": "Barva",
  "catVariables": "Proměnné",
  "catFunctions": "Funkce",
  "listVariable": "seznam",
  "textVariable": "text",
  "badXml": "Chyba při parsování XML:\n%1\n\nVyberte 'OK' pro opuštění změn nebo 'Zrušit' pro další úpravu XML.",
  
  "c_Objects" : "Objekty",
  "c_Blocks" : "Bloky",
  "c_Mobs" : "Mobové",
  "c_Items" : "Předměty",
  "c_Time" : "Čas",
  "c_Movement" : "Pohyb",
  "c_Actions" : "Akce",
  "c_Drawing" : "Kreslení",
  "c_Events" : "Události",
  "c_Status" : "Stav",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Příklady ...",
  "c_Examples" : "Příklady",
  "c_Algorithms" : "Algoritmy",
  "t_saveTooltip" : "Uložte program do počítače",
  "t_readTooltip" : "Načíst program z počítače",
  "warn_entername" :  "JMÉNO HRÁČE MINECRAFT chybí v pravém horním poli",
  "info_deploySuccess" :  "Program je připraven v Minecraftu pro %2",
  "info_deploySuccessWithWarning" :  "Program je připraven v Minecraftu, ale %2 není online",
  "info_deployUnknownPlayer" :  "Mojang nemá hráče s jménem %2",
  "infiniteLoopMessage" : "Program byl zastaven, protože byl detekován nekonečný cyklus"
}