var MSG = {
  "title": "Κώδικας",
  "blocks": "Μπλοκ",
  "runTooltip": "Εκτέλεσε το πρόγραμμα που ορίζεται από τα blocks στον χώρο εργασίας.",
  "timeout": "Έχει ξεπεραστεί ο μέγιστος αριθμός επαναλήψεων εκτέλεσης.",
  "trashTooltip": "Απόρριψη όλων των μπλοκ.",
  "catLogic": "Λογική",
  "catLoops": "Βρόχοι",
  "catMath": "Μαθηματικά",
  "catText": "Κείμενο",
  "catLists": "Λίστες",
  "catColour": "Χρώμα",
  "catVariables": "Μεταβλητές",
  "catFunctions": "Συναρτήσεις",
  "listVariable": "λίστα",
  "textVariable": "κείμενο",
  "badXml": "Σφάλμα ανάλυσης XML:\n%1\n\nΕπιλέξτε «ΟΚ» για να αγνοήσετε τις αλλαγές σας ή «Ακύρο» για περαιτέρω επεξεργασία του XML.",
  "c_Objects": "Αντικείμενα",
  "c_Blocks": "Μπλοκ",
  "c_Mobs": "Πλάσματα",
  "c_Items": "Αντικείμενα",
  "c_Time": "Χρόνος",
  "c_Movement": "Κίνηση",
  "c_Actions": "Ενέργειες",
  "c_Drawing": "Σχεδίαση",
  "c_Events": "Γεγονότα",
  "c_Status": "Κατάσταση",
  "c_Python": "Python",
  "c_ExamplesMenu": "Παραδείγματα ...",
  "c_Examples": "Παραδείγματα",
  "c_Algorithms": "Αλγόριθμοι",
  "t_saveTooltip": "Αποθήκευση του προγράμματος στον υπολογιστή",
  "t_readTooltip": "Φόρτωση ενός προγράμματος από τον υπολογιστή",
  "warn_entername": "Το όνομα παίκτη του MINECRAFT λείπει από το πεδίο πάνω δεξιά",
  "info_deploySuccess": "Το πρόγραμμα είναι έτοιμο στο Minecraft για %2",
  "info_deploySuccessWithWarning": "Το πρόγραμμα είναι έτοιμο στο Minecraft, αλλά το %2 δεν είναι συνδεδεμένο",
  "info_deployUnknownPlayer": "Η Mojang δεν έχει παίκτη με το όνομα %2",
  "infiniteLoopMessage": "Το πρόγραμμα σταμάτησε επειδή εντοπίστηκε άπειρος βρόχος"
}