var MSG = {
  title: "Kood",
  blocks: "Blokid",
  runTooltip: "Käivita tööruumis plokkide abil määratletud programm.",
  timeout: "Maksimaalne täitmise iteratsioonide arv ületatud.",
  trashTooltip: "Kustuta kõik plokid.",
  catLogic: "Loogika",
  catLoops: "Tsüklid",
  catMath: "Matemaatika",
  catText: "Tekst",
  catLists: "Loendid",
  catColour: "Värv",
  catVariables: "Muutujad",
  catFunctions: "Funktsioonid",
  listVariable: "loend",
  textVariable: "tekst",
  badXml: "Viga XML-i parsimisel:\n%1\n\nVali 'OK' et hüljata muudatused või 'Loobu' et jätkata XML-i redigeerimist.",
	  
  c_Objects : "Objektid",
  c_Blocks : "Plokid",
  c_Mobs : "Mobid",
  c_Items : "Esemed",
  c_Time : "Aeg",
  c_Movement : "Liikumine",
  c_Actions : "Toimingud",
  c_Drawing : "Joonistamine",
  c_Events : "Sündmused",
  c_Status : "Seisund",
  c_Python : "Python",
  c_ExamplesMenu : "Näited ...",
  c_Examples : "Näited",
  c_Algorithms : "Algoritmid",
  t_saveTooltip : "Salvesta programm arvutisse",
  t_readTooltip : "Laadi programm arvutist",
  warn_entername :  "MINECRAFTI MÄNGIJA NIMI puudub paremas ülaosas asuvas väljas",
  info_deploySuccess :  "Programm on Minecraftis valmis %2 jaoks",
  info_deploySuccessWithWarning :  "Programm on Minecraftis valmis, kuid %2 ei ole võrgus",
  info_deployUnknownPlayer :  "Mojangul pole mängijat nimega %2",
  infiniteLoopMessage : "Programm on peatatud, kuna tuvastati lõpmatu tsükkel"
};