var MSG = {
  title: "Code",
  blocks: "Blocs",
  runTooltip: "Exécuter le programme défini par les blocs dans l'espace de travail.",
  timeout: "Nombre maximal d'itérations d'exécution dépassé.",
  trashTooltip: "Supprimer tous les blocs.",
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Mathématiques",
  catText: "Texte",
  catLists: "Listes",
  catColour: "Couleur",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  listVariable: "liste",
  textVariable: "texte",
  badXml: "Erreur lors de l'analyse du XML:\n%1\n\nSélectionnez 'OK' pour abandonner vos modifications ou 'Annuler' pour continuer à modifier le XML.",
	  
  c_Objects : "Objets",
  c_Blocks : "Blocs",
  c_Mobs : "Monstres",
  c_Items : "Objets",
  c_Time : "Temps",
  c_Movement : "Mouvement",
  c_Actions : "Actions",
  c_Drawing : "Dessin",
  c_Events : "Événements",
  c_Status : "État",
  c_Python : "Python",
  c_ExamplesMenu : "Exemples ...",
  c_Examples : "Exemples",
  c_Algorithms : "Algorithmes",
  t_saveTooltip : "Enregistrer le programme sur l'ordinateur",
  t_readTooltip : "Charger un programme depuis l'ordinateur",
  warn_entername :  "Le NOM DU JOUEUR MINECRAFT est manquant dans le champ en haut à droite",
  info_deploySuccess :  "Le programme est prêt dans Minecraft pour %2",
  info_deploySuccessWithWarning :  "Le programme est prêt dans Minecraft mais %2 n'est pas en ligne",
  info_deployUnknownPlayer :  "Mojang ne dispose pas d'un joueur nommé %2",
  infiniteLoopMessage : "Le programme s'est arrêté car une boucle infinie a été détectée"

};