var MSG = {
  "title": "कोड",
  "blocks": "ब्लॉक्स",
  "runTooltip": "वर्कस्पेस में ब्लॉक्स द्वारा परिभाषित कार्यक्रम चलाएं।",
  "timeout": "अधिकतम निष्पादन पुनरावृत्तियाँ पार हो गईं।",
  "trashTooltip": "सभी ब्लॉक्स हटाएं।",
  "catLogic": "तर्क",
  "catLoops": "लूप",
  "catMath": "गणित",
  "catText": "पाठ",
  "catLists": "सूचियाँ",
  "catColour": "रंग",
  "catVariables": "चर",
  "catFunctions": "कार्य",
  "listVariable": "सूची",
  "textVariable": "पाठ",
  "badXml": "XML को पार्स करने में त्रुटि:\n%1\n\nअपने परिवर्तन छोड़ने के लिए 'OK' चुनें या XML को और संपादित करने के लिए 'Cancel' चुनें।",
  "c_Objects": "ऑब्जेक्ट्स",
  "c_Blocks": "ब्लॉक्स",
  "c_Mobs": "मोब्स",
  "c_Items": "आइटम्स",
  "c_Time": "समय",
  "c_Movement": "गतिशीलता",
  "c_Actions": "क्रियाएँ",
  "c_Drawing": "चित्रण",
  "c_Events": "घटनाएँ",
  "c_Status": "स्थिति",
  "c_Python": "पायथन",
  "c_ExamplesMenu": "उदाहरण ...",
  "c_Examples": "उदाहरण",
  "c_Algorithms": "एल्गोरिदम",
  "t_saveTooltip": "कंप्यूटर पर कार्यक्रम सहेजें",
  "t_readTooltip": "कंप्यूटर से कार्यक्रम लोड करें",
  "warn_entername": "ऊपर दाईं ओर फ़ील्ड में माइनक्राफ्ट प्लेयर नाम गायब है",
  "info_deploySuccess": "Minecraft में %2 के लिए कार्यक्रम तैयार है",
  "info_deploySuccessWithWarning": "Minecraft में कार्यक्रम तैयार है लेकिन %2 ऑनलाइन नहीं है",
  "info_deployUnknownPlayer": "Mojang के पास %2 नाम का कोई खिलाड़ी नहीं है",
  "infiniteLoopMessage": "अनंत लूप का पता चलने के कारण कार्यक्रम रोक दिया गया"
}