var MSG = {
  "title": "Kod",
  "blocks": "Blokovi",
  "runTooltip": "Pokreni program definiran blokovima u radnom prostoru.",
  "timeout": "Prekoračen je maksimalan broj izvedbenih iteracija.",
  "trashTooltip": "Odbaci sve blokove.",
  "catLogic": "Logika",
  "catLoops": "Petlje",
  "catMath": "Matematika",
  "catText": "Tekst",
  "catLists": "Popisi",
  "catColour": "Boja",
  "catVariables": "Varijable",
  "catFunctions": "Funkcije",
  "listVariable": "popis",
  "textVariable": "tekst",
  "badXml": "Greška pri parsiranju XML:\n%1\n\nOdaberite 'OK' da biste odustali od promjena ili 'Otkaži' za daljnje uređivanje XML-a.",
  "c_Objects": "Objekti",
  "c_Blocks": "Blokovi",
  "c_Mobs": "Mobovi",
  "c_Items": "Predmeti",
  "c_Time": "Vrijeme",
  "c_Movement": "Kretanje",
  "c_Actions": "Radnje",
  "c_Drawing": "Crtanje",
  "c_Events": "Događaji",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Primjeri ...",
  "c_Examples": "Primjeri",
  "c_Algorithms": "Algoritmi",
  "t_saveTooltip": "Spremi program na računalo",
  "t_readTooltip": "Učitaj program s računala",
  "warn_entername": "IME IGRAČA MINECRAFTA nedostaje u gornjem desnom polju",
  "info_deploySuccess": "Program je spreman u Minecraftu za %2",
  "info_deploySuccessWithWarning": "Program je spreman u Minecraftu, ali %2 nije online",
  "info_deployUnknownPlayer": "Mojang nema igrača pod imenom %2",
  "infiniteLoopMessage": "Program je zaustavljen jer je otkrivena beskonačna petlja"
}