var MSG = {
  "title": "Kód",
  "blocks": "Blokkok",
  "runTooltip": "A blokkok által a munkaterületen meghatározott program futtatása.",
  "timeout": "A maximális végrehajtási iterációk száma meghaladva.",
  "trashTooltip": "Az összes blokk eldobása.",
  "catLogic": "Logika",
  "catLoops": "Ciklusok",
  "catMath": "Matematika",
  "catText": "Szöveg",
  "catLists": "Listák",
  "catColour": "Szín",
  "catVariables": "Változók",
  "catFunctions": "Függvények",
  "listVariable": "lista",
  "textVariable": "szöveg",
  "badXml": "Hiba az XML értelmezése közben:\n%1\n\nVálassza az 'OK'-t a módosítások elvetéséhez vagy a 'Mégse'-t az XML további szerkesztéséhez.",
  
  "c_Objects": "Objektumok",
  "c_Blocks": "Blokkok",
  "c_Mobs": "Mobok",
  "c_Items": "Tárgyak",
  "c_Time": "Idő",
  "c_Movement": "Mozgás",
  "c_Actions": "Műveletek",
  "c_Drawing": "Rajzolás",
  "c_Events": "Események",
  "c_Status": "Állapot",
  "c_Python": "Python",
  "c_ExamplesMenu": "Példák ...",
  "c_Examples": "Példák",
  "c_Algorithms": "Algoritmusok",
  "t_saveTooltip": "A program mentése a számítógépre",
  "t_readTooltip": "Program betöltése a számítógépről",
  "warn_entername": "A MINECRAFT JÁTÉKOS NEVE hiányzik a jobb felső mezőben",
  "info_deploySuccess": "A program Minecraftban készen áll a(z) %2 számára.",
  "info_deploySuccessWithWarning": "A program Minecraftban készen áll, de %2 nincs online.",
  "info_deployUnknownPlayer": "A Mojang nem talál olyan játékost, akinek a neve %2.",
  "infiniteLoopMessage": "A program megállt, mert végtelen hurkot észlelt"
}