var MSG = {
  "title": "Kode",
  "blocks": "Blok",
  "runTooltip": "Jalankan program yang didefinisikan oleh blok-blok di ruang kerja.",
  "timeout": "Maksimum iterasi eksekusi terlampaui.",
  "trashTooltip": "Hapus semua blok.",
  "catLogic": "Logika",
  "catLoops": "Perulangan",
  "catMath": "Matematika",
  "catText": "Teks",
  "catLists": "Daftar",
  "catColour": "Warna",
  "catVariables": "Variabel",
  "catFunctions": "Fungsi",
  "listVariable": "daftar",
  "textVariable": "teks",
  "badXml": "Kesalahan saat memparsing XML:\n%1\n\nPilih 'OK' untuk membatalkan perubahan Anda atau 'Cancel' untuk mengedit XML lebih lanjut.",
  
  "c_Objects": "Objek",
  "c_Blocks": "Blok",
  "c_Mobs": "Makhluk",
  "c_Items": "Barang",
  "c_Time": "Waktu",
  "c_Movement": "Gerakan",
  "c_Actions": "Tindakan",
  "c_Drawing": "Gambar",
  "c_Events": "Peristiwa",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Contoh ...",
  "c_Examples": "Contoh",
  "c_Algorithms": "Algoritma",
  "t_saveTooltip": "Simpan program ke komputer",
  "t_readTooltip": "Muat program dari komputer",
  "warn_entername": "NAMA PEMAIN MINECRAFT hilang di kolom kanan atas",
  "info_deploySuccess": "Program siap di Minecraft untuk %2",
  "info_deploySuccessWithWarning": "Program siap di Minecraft tetapi %2 tidak online",
  "info_deployUnknownPlayer": "Mojang tidak memiliki pemain bernama %2",
  "infiniteLoopMessage": "Program berhenti karena terdeteksi loop tak terhingga"
}