var MSG = {
  "title": "Koodu",
  "blocks": "Blọkị",
  "runTooltip": "Gbaa mmemme a kọwara site na blọkị nọ na oghere ọrụ.",
  "timeout": "Agwụla ọnụ ọgụgụ iterations kacha elu.",
  "trashTooltip": "Wepụ blọkị niile.",
  "catLogic": "Ụkpụrụ",
  "catLoops": "Mgba",
  "catMath": "Ụmụ ọnụọgụ",
  "catText": "Ederede",
  "catLists": "Ndepụta",
  "catColour": "Agba",
  "catVariables": "Mgbanwe",
  "catFunctions": "Ọrụ",
  "listVariable": "ndepụta",
  "textVariable": "ederede",
  "badXml": "Nsogbu ịkọwa XML:\n%1\n\nHọrọ 'OK' iji hapụ mgbanwe gị ma ọ bụ 'Cancel' iji degharịa XML ọzọ.",
  
  "c_Objects" : "Ihe",
  "c_Blocks" : "Blọkị",
  "c_Mobs" : "Ndị bi ndụ",
  "c_Items" : "Ihe ndị",
  "c_Time" : "Oge",
  "c_Movement" : "Mmegharị",
  "c_Actions" : "Ihe omume",
  "c_Drawing" : "Ịkpụzi",
  "c_Events" : "Ihe omume",
  "c_Status" : "Ọnọdụ",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Ihe nlere ...",
  "c_Examples" : "Nlere",
  "c_Algorithms" : "Algọritm",
  "t_saveTooltip" : "Chekwaa mmemme na kọmputa",
  "t_readTooltip" : "Bulite mmemme site na kọmputa",
  "warn_entername" :  "Aha onye egwuregwu MINECRAFT adịghị na ubi dị n'elu aka nri",
  "info_deploySuccess" :  "Mmemme ahụ dị njikere na Minecraft maka %2",
  "info_deploySuccessWithWarning" :  "Mmemme ahụ dị njikere na Minecraft ma %2 anaghị ewere online",
  "info_deployUnknownPlayer" :  "Mojang enweghị onye egwuregwu akpọrọ %2",
  "infiniteLoopMessage" : "Mmemme akwụsịrị n’ihi na achọpụtara loop na-adịghị agwụcha"
}