var MSG = {
  "title": "コード",
  "blocks": "ブロック",
  "runTooltip": "ワークスペース内のブロックで定義されたプログラムを実行します。",
  "timeout": "最大実行回数を超えました。",
  "trashTooltip": "すべてのブロックを削除します。",
  "catLogic": "ロジック",
  "catLoops": "ループ",
  "catMath": "数学",
  "catText": "テキスト",
  "catLists": "リスト",
  "catColour": "色",
  "catVariables": "変数",
  "catFunctions": "関数",
  "listVariable": "リスト",
  "textVariable": "テキスト",
  "badXml": "XML の解析エラー:\n%1\n\n変更を破棄するには 'OK' を、XML をさらに編集するには 'Cancel' を選択してください。",
  "c_Objects": "オブジェクト",
  "c_Blocks": "ブロック",
  "c_Mobs": "モブ",
  "c_Items": "アイテム",
  "c_Time": "時間",
  "c_Movement": "移動",
  "c_Actions": "アクション",
  "c_Drawing": "描画",
  "c_Events": "イベント",
  "c_Status": "状態",
  "c_Python": "Python",
  "c_ExamplesMenu": "例 ...",
  "c_Examples": "例",
  "c_Algorithms": "アルゴリズム",
  "t_saveTooltip": "プログラムをコンピュータに保存します",
  "t_readTooltip": "コンピュータからプログラムを読み込みます",
  "warn_entername": "右上のフィールドに Minecraft のプレイヤー名が入力されていません",
  "info_deploySuccess": "Minecraft で %2 のプログラムが用意できました",
  "info_deploySuccessWithWarning": "Minecraft でプログラムは用意できましたが %2 がオンラインではありません",
  "info_deployUnknownPlayer": "Mojang には %2 というプレイヤーは存在しません",
  "infiniteLoopMessage": "無限ループが検出されたため、プログラムを停止しました"
}