var MSG = {
  title: "코드",
  blocks: "블록",
  runTooltip: "작업 공간의 블록으로 정의된 프로그램을 실행합니다.",
  timeout: "최대 실행 반복 횟수를 초과했습니다.",
  trashTooltip: "모든 블록을 삭제합니다.",
  catLogic: "논리",
  catLoops: "루프",
  catMath: "수학",
  catText: "텍스트",
  catLists: "리스트",
  catColour: "색상",
  catVariables: "변수",
  catFunctions: "함수",
  listVariable: "리스트",
  textVariable: "텍스트",
  badXml: "XML 구문 분석 오류:\n%1\n\n변경 내용을 포기하려면 '확인'을 선택하거나 XML 편집을 계속하려면 '취소'를 선택합니다.",
  
  c_Objects : "객체",
  c_Blocks : "블록",
  c_Mobs : "몹",
  c_Items : "아이템",
  c_Time : "시간",
  c_Movement : "이동",
  c_Actions : "동작",
  c_Drawing : "그리기",
  c_Events : "이벤트",
  c_Status : "상태",
  c_Python : "파이썬",
  c_ExamplesMenu : "예제 ...",
  c_Examples : "예제",
  c_Algorithms : "알고리즘",
  t_saveTooltip : "컴퓨터에 프로그램 저장",
  t_readTooltip : "컴퓨터에서 프로그램 불러오기",
  warn_entername :  "오른쪽 상단 필드에 마인크래프트 플레이어 이름이 누락되어 있습니다",
  info_deploySuccess :  "마인크래프트에서 %2용 프로그램이 준비되었습니다",
  info_deploySuccessWithWarning :  "마인크래프트에서 프로그램이 준비되었지만 %2가 온라인 상태가 아닙니다",
  info_deployUnknownPlayer :  "Mojang에는 %2라는 플레이어가 없습니다",
  infiniteLoopMessage : "무한 루프가 감지되어 프로그램이 중지되었습니다"

};