var MSG = {
  "title": "Kods",
  "blocks": "Bloki",
  "runTooltip": "Palaidiet programmu, ko definē blokos darba telpā.",
  "timeout": "Pārsniegts maksimālais izpildes iterāciju skaits.",
  "trashTooltip": "Izmetiet visus blokus.",
  "catLogic": "Loģika",
  "catLoops": "Cikli",
  "catMath": "Matemātika",
  "catText": "Teksts",
  "catLists": "Saraksti",
  "catColour": "Krāsa",
  "catVariables": "Mainīgie",
  "catFunctions": "Funkcijas",
  "listVariable": "Saraksts",
  "textVariable": "Teksts",
  "badXml": "Kļūda, parsējot XML:\n%1\n\nIzvēlieties 'Labi' lai atmestu savas izmaiņas vai 'Atcelt' lai turpinātu labot XML.",
  
  "c_Objects" : "Objekti",
  "c_Blocks" : "Bloki",
  "c_Mobs" : "Monstri",
  "c_Items" : "Priekšmeti",
  "c_Time" : "Laiks",
  "c_Movement" : "Kustība",
  "c_Actions" : "Darbības",
  "c_Drawing" : "Zīmēšana",
  "c_Events" : "Notikumi",
  "c_Status" : "Statuss",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Piemēri ...",
  "c_Examples" : "Piemēri",
  "c_Algorithms" : "Algoritmi",
  "t_saveTooltip" : "Saglabāt programmu datorā",
  "t_readTooltip" : "Ielādēt programmu no datora",
  "warn_entername" :  "Minecraft spēlētāja vārds trūkst augšējajā labajā laukā",
  "info_deploySuccess" :  "Programma ir gatava Minecraftam %2",
  "info_deploySuccessWithWarning" :  "Programma ir gatava Minecraftam, bet %2 nav tiešsaistē",
  "info_deployUnknownPlayer" :  "Mojangam nav spēlētāja ar nosaukumu %2",
  "infiniteLoopMessage" : "Programma pārtraukta, jo tika konstatēta bezgalīga cilpa"
}