var MSG = {
  "title": "Код",
  "blocks": "Блокови",
  "runTooltip": "Изврши ја програмата дефинирана преку блоковите во работниот простор.",
  "timeout": "Достигнат е максимумот на итерации за извршување.",
  "trashTooltip": "Отфрли ги сите блокови.",
  "catLogic": "Логика",
  "catLoops": "Циклуси",
  "catMath": "Математика",
  "catText": "Текст",
  "catLists": "Листи",
  "catColour": "Боја",
  "catVariables": "Променливи",
  "catFunctions": "Функции",
  "listVariable": "лист",
  "textVariable": "текст",
  "badXml": "Грешка при обработката на XML:\n%1\n\nИзбери 'OK' за да ги отфрлиш промените или 'Cancel' за дополнително уредување на XML.",
  
  "c_Objects": "Објекти",
  "c_Blocks": "Блокови",
  "c_Mobs": "Моби",
  "c_Items": "Предмети",
  "c_Time": "Време",
  "c_Movement": "Движење",
  "c_Actions": "Акции",
  "c_Drawing": "Цртање",
  "c_Events": "Настани",
  "c_Status": "Статус",
  "c_Python": "Питон",
  "c_ExamplesMenu": "Примери ...",
  "c_Examples": "Примери",
  "c_Algorithms": "Алгоритми",
  "t_saveTooltip": "Зачувај ја програмата на компјутерот",
  "t_readTooltip": "Вчитај програма од компјутерот",
  "warn_entername": "Името на играчот во Minecraft недостасува во полето во горниот десен агол",
  "info_deploySuccess": "Програмата е подготвена во Minecraft за %2",
  "info_deploySuccessWithWarning": "Програмата е подготвена во Minecraft, но %2 не е онлајн",
  "info_deployUnknownPlayer": "Mojang нема играч со име %2",
  "infiniteLoopMessage": "Програмата е запрена поради детекција на бесконечен циклус"
}