var MSG = {
  title: "Kod",
  blocks: "Blok",
  runTooltip: "Jalankan program yang ditakrifkan oleh blok dalam ruang kerja.",
  timeout: "Melebihi bilangan iterasi pelaksanaan maksimum.",
  trashTooltip: "Buang semua blok.",
  catLogic: "Logik",
  catLoops: "Ulangan",
  catMath: "Matematik",
  catText: "Teks",
  catLists: "Senarai",
  catColour: "Warna",
  catVariables: "Pembolehubah",
  catFunctions: "Fungsi",
  listVariable: "senarai",
  textVariable: "teks",
  badXml: "Ralat semasa mengurai XML:\n%1\n\nPilih 'OK' untuk membuang perubahan anda atau 'Batal' untuk mengedit XML lanjut.",
  
  c_Objects : "Objek",
  c_Blocks : "Blok",
  c_Mobs : "Makhluk",
  c_Items : "Item",
  c_Time : "Masa",
  c_Movement : "Pergerakan",
  c_Actions : "Tindakan",
  c_Drawing : "Lukisan",
  c_Events : "Peristiwa",
  c_Status : "Status",
  c_Python : "Python",
  c_ExamplesMenu : "Contoh ...",
  c_Examples : "Contoh",
  c_Algorithms : "Algoritma",
  t_saveTooltip : "Simpan program di komputer",
  t_readTooltip : "Buka program dari komputer",
  warn_entername :  "NAMA PEMAIN MINECRAFT hilang dalam medan di kanan atas",
  info_deploySuccess :  "Program siap di Minecraft untuk %2",
  info_deploySuccessWithWarning :  "Program telah siap di Minecraft tetapi %2 tidak dalam talian",
  info_deployUnknownPlayer :  "Mojang tidak mempunyai pemain bernama %2",
  infiniteLoopMessage : "Program berhenti kerana dikesan gelung tak terhingga"
};