var MSG = {
  "title": "Code",
  "blocks": "Blokken",
  "runTooltip": "Voer het programma uit dat is gedefinieerd door de blokken in de werkruimte.",
  "timeout": "Maximale uitvoeringsiteraties overschreden.",
  "trashTooltip": "Verwijder alle blokken.",
  "catLogic": "Logica",
  "catLoops": "Lussen",
  "catMath": "Wiskunde",
  "catText": "Tekst",
  "catLists": "Lijsten",
  "catColour": "Kleur",
  "catVariables": "Variabelen",
  "catFunctions": "Functies",
  "listVariable": "lijst",
  "textVariable": "tekst",
  "badXml": "Fout bij het inlezen van XML:\\n%1\\n\\nKies 'OK' om uw wijzigingen te laten vallen of 'Annuleren' om de XML verder te bewerken.",
  "c_Objects": "Objecten",
  "c_Blocks": "Blokken",
  "c_Mobs": "Wezens",
  "c_Items": "Items",
  "c_Time": "Tijd",
  "c_Movement": "Beweging",
  "c_Actions": "Acties",
  "c_Drawing": "Tekenen",
  "c_Events": "Gebeurtenissen",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Voorbeelden ...",
  "c_Examples": "Voorbeelden",
  "c_Algorithms": "Algoritmes",
  "t_saveTooltip": "Sla het programma op op de computer.",
  "t_readTooltip": "Laad een programma vanaf de computer.",
  "warn_entername": "De MINECRAFT-spelernaam ontbreekt in het veld rechtsboven.",
  "info_deploySuccess": "Het programma is klaar in Minecraft voor %2",
  "info_deploySuccessWithWarning": "Het programma is klaar in Minecraft maar %2 is niet online",
  "info_deployUnknownPlayer": "Mojang heeft geen speler genaamd %2",
  "infiniteLoopMessage": "Programma gestopt omdat er een oneindige lus is gedetecteerd."
}