var MSG = {
  title: "Código",
  blocks: "Blocos",
  runTooltip: "Executar o programa definido pelos blocos no espaço de trabalho.",
  timeout: "Limite máximo de iterações de execução excedido.",
  trashTooltip: "Descartar todos os blocos.",
  catLogic: "Lógica",
  catLoops: "Laços",
  catMath: "Matemática",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Cor",
  catVariables: "Variáveis",
  catFunctions: "Funções",
  listVariable: "lista",
  textVariable: "texto",
  badXml: "Erro ao analisar XML:\n%1\n\nSelecione 'OK' para abandonar suas alterações ou 'Cancelar' para editar ainda mais o XML.",
  
  c_Objects : "Objetos",
  c_Blocks : "Blocos",
  c_Mobs : "Criaturas",
  c_Items : "Itens",
  c_Time : "Tempo",
  c_Movement : "Movimento",
  c_Actions : "Ações",
  c_Drawing : "Desenho",
  c_Events : "Eventos",
  c_Status : "Status",
  c_Python : "Python",
  c_ExamplesMenu : "Exemplos ...",
  c_Examples : "Exemplos",
  c_Algorithms : "Algoritmos",
  t_saveTooltip : "Salvar o programa no computador",
  t_readTooltip : "Carregar um programa do computador",
  warn_entername :  "O NOME DO JOGADOR DO MINECRAFT está ausente no campo do canto superior direito",
  info_deploySuccess :  "O programa está pronto no Minecraft para %2",
  info_deploySuccessWithWarning :  "O programa está pronto no Minecraft, mas %2 não está online",
  info_deployUnknownPlayer :  "A Mojang não tem um jogador chamado %2",
  infiniteLoopMessage : "O programa foi interrompido porque foi detectado um loop infinito"

};