var MSG = {
  "title": "Код",
  "blocks": "Блоки",
  "runTooltip": "Запустить программу, определённую блоками на рабочем пространстве.",
  "timeout": "Превышено максимальное число итераций выполнения.",
  "trashTooltip": "Удалить все блоки.",
  "catLogic": "Логика",
  "catLoops": "Циклы",
  "catMath": "Математика",
  "catText": "Текст",
  "catLists": "Списки",
  "catColour": "Цвет",
  "catVariables": "Переменные",
  "catFunctions": "Функции",
  "listVariable": "список",
  "textVariable": "текст",
  "badXml": "Ошибка разбора XML:\n%1\n\nВыберите 'OK', чтобы отказаться от изменений, или 'Cancel' — продолжить редактирование XML.",
  
  "c_Objects" : "Объекты",
  "c_Blocks" : "Блоки",
  "c_Mobs" : "Мобы",
  "c_Items" : "Предметы",
  "c_Time" : "Время",
  "c_Movement" : "Движение",
  "c_Actions" : "Действия",
  "c_Drawing" : "Рисование",
  "c_Events" : "События",
  "c_Status" : "Статус",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Примеры ...",
  "c_Examples" : "Примеры",
  "c_Algorithms" : "Алгоритмы",
  "t_saveTooltip" : "Сохранить программу на компьютере",
  "t_readTooltip" : "Загрузить программу с компьютера",
  "warn_entername" : "Имя игрока Minecraft отсутствует в поле в правом верхнем углу",
  "info_deploySuccess" : "Программа готова в Minecraft для %2",
  "info_deploySuccessWithWarning" : "Программа готова в Minecraft, но %2 не онлайн",
  "info_deployUnknownPlayer" : "У Mojang нет игрока с именем %2",
  "infiniteLoopMessage" : "Программа остановлена из-за обнаружения бесконечного цикла"
}