var MSG = {
  "title": "Koda",
  "blocks": "Bloki",
  "runTooltip": "Zaženi program, ki ga definirajo bloki na delovnem prostoru.",
  "timeout": "Preseženo je največje število izvedbenih ponovitev.",
  "trashTooltip": "Izbriši vse bloke.",
  "catLogic": "Logika",
  "catLoops": "Zanke",
  "catMath": "Matematika",
  "catText": "Besedilo",
  "catLists": "Seznami",
  "catColour": "Barva",
  "catVariables": "Spremenljivke",
  "catFunctions": "Funkcije",
  "listVariable": "seznam",
  "textVariable": "besedilo",
  "badXml": "Napaka pri razčlenjevanju XML:\n%1\n\nIzberite 'OK' za opustitev sprememb ali 'Prekliči' za nadaljevanje urejanja XML.",
  "c_Objects": "Objekti",
  "c_Blocks": "Bloki",
  "c_Mobs": "Mobovi",
  "c_Items": "Predmeti",
  "c_Time": "Čas",
  "c_Movement": "Gibanje",
  "c_Actions": "Akcije",
  "c_Drawing": "Risanje",
  "c_Events": "Dogodki",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Primeri ...",
  "c_Examples": "Primeri",
  "c_Algorithms": "Algoritmi",
  "t_saveTooltip": "Shrani program na računalnik",
  "t_readTooltip": "Naloži program iz računalnika",
  "warn_entername": "IME IGRALCA MINECRAFT manjka v zgornjem desnem polju",
  "info_deploySuccess": "Program je pripravljen v Minecraftu za %2",
  "info_deploySuccessWithWarning": "Program je pripravljen v Minecraftu, vendar %2 ni povezan z internetom",
  "info_deployUnknownPlayer": "Mojang nima igralca z imenom %2",
  "infiniteLoopMessage": "Program se je ustavil, ker je bila zaznana neskončna zanka"
}