var MSG = {
  "title": "Kodi",
  "blocks": "Blloqe",
  "runTooltip": "Ekzekuto programin e përcaktuar nga blloqet në hapësirën e punës.",
  "timeout": "U tejkalua numri maksimal i përsëritjeve të ekzekutimit.",
  "trashTooltip": "Hiq të gjitha blloqet.",
  "catLogic": "Logjika",
  "catLoops": "Ciklet",
  "catMath": "Matematikë",
  "catText": "Tekst",
  "catLists": "Listat",
  "catColour": "Ngjyra",
  "catVariables": "Variablat",
  "catFunctions": "Funksionet",
  "listVariable": "listë",
  "textVariable": "tekst",
  "badXml": "Gabim gjatë parsimit të XML:\n%1\n\nZgjidh 'OK' për të hequr dorë nga ndryshimet e tua ose 'Anulo' për të vazhduar redaktimin e XML-së.",
  
  "c_Objects" : "Objektet",
  "c_Blocks" : "Blloqe",
  "c_Mobs" : "Mobët",
  "c_Items" : "Artikujt",
  "c_Time" : "Koha",
  "c_Movement" : "Lëvizje",
  "c_Actions" : "Veprimet",
  "c_Drawing" : "Vizatim",
  "c_Events" : "Ngjarjet",
  "c_Status" : "Statusi",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "Shembujt ...",
  "c_Examples" : "Shembujt",
  "c_Algorithms" : "Algoritmet",
  "t_saveTooltip" : "Ruaj programin në kompjuterin",
  "t_readTooltip" : "Lexo një program nga kompjuteri",
  "warn_entername" :  "Emri i lojtarit të Minecraft-it mungon në fushën e sipërme të djathtë.",
  "info_deploySuccess" :  "Programi është gati në Minecraft për %2",
  "info_deploySuccessWithWarning" :  "Programi është gati në Minecraft por %2 nuk është online",
  "info_deployUnknownPlayer" :  "Mojang nuk ka një lojtar të quajtur %2",
  "infiniteLoopMessage" : "Programi u ndal sepse u zbulua një cikël i pandërprerë"
}