var MSG = {
  "title": "Kod",
  "blocks": "Blokovi",
  "runTooltip": "Pokreni program definisan blokovima u radnom prostoru.",
  "timeout": "Prekoračen je maksimalan broj iteracija.",
  "trashTooltip": "Obriši sve blokove.",
  "catLogic": "Logika",
  "catLoops": "Petlje",
  "catMath": "Matematika",
  "catText": "Tekst",
  "catLists": "Liste",
  "catColour": "Boja",
  "catVariables": "Promenljive",
  "catFunctions": "Funkcije",
  "listVariable": "lista",
  "textVariable": "tekst",
  "badXml": "Greška pri parsiranju XML:\n%1\n\nOdaberite 'OK' da biste odustali od promena ili 'Cancel' da nastavite uređivanje XML-a.",
  "c_Objects": "Objekti",
  "c_Blocks": "Blokovi",
  "c_Mobs": "Mobovi",
  "c_Items": "Predmeti",
  "c_Time": "Vreme",
  "c_Movement": "Kretanje",
  "c_Actions": "Akcije",
  "c_Drawing": "Crtanje",
  "c_Events": "Događaji",
  "c_Status": "Status",
  "c_Python": "Python",
  "c_ExamplesMenu": "Primeri ...",
  "c_Examples": "Primeri",
  "c_Algorithms": "Algoritmi",
  "t_saveTooltip": "Sačuvaj program na računaru",
  "t_readTooltip": "Učitaj program sa računara",
  "warn_entername": "Minecraft korisničko ime nedostaje u polju na desnoj gornjoj strani",
  "info_deploySuccess": "Program je spreman u Minecraft-u za %2",
  "info_deploySuccessWithWarning": "Program je spreman u Minecraft-u, ali %2 nije online",
  "info_deployUnknownPlayer": "Mojang nema igrača pod imenom %2",
  "infiniteLoopMessage": "Program je zaustavljen jer je otkriven beskonačni ciklus"
}