var MSG = {
  "title": "கோடு",
  "blocks": "பிளாக்குகள்",
  "runTooltip": "வேலைப்பகுதியில் பிளாக்குகள் மூலம் வரையறுக்கப்பட்ட நிரலை இயக்கவும்.",
  "timeout": "செயலாக்கத்தின் அதிகபட்ச முறைமைகள் மீறிவிட்டன.",
  "trashTooltip": "எல்லா பிளாக்களையும் எறிக்கவும்.",
  "catLogic": "தர்க்கம்",
  "catLoops": "சுழற்சிகள்",
  "catMath": "கணிதம்",
  "catText": "உரை",
  "catLists": "பட்டியல்கள்",
  "catColour": "வண்ணம்",
  "catVariables": "மாறிகள்",
  "catFunctions": "செயல்பாடுகள்",
  "listVariable": "பட்டியல்",
  "textVariable": "உரை",
  "badXml": "XML-ஐ பகுப்பாய்வு செய்யும் போது பிழை:\n%1\n\nமாற்றங்களை விட்டு செல்ல 'சரி' என்பதனைத் தேர்வு செய்யவும் அல்லது XML-ஐ மேலும் தொகுப்பதற்கு 'ரத்துசெய்' என்பதையும் தேர்வு செய்யவும்.",
  
  "c_Objects": "பெொருட்கள்",
  "c_Blocks": "பிளாக்குகள்",
  "c_Mobs": "மாப்ஸ்",
  "c_Items": "உருப்படிகள்",
  "c_Time": "நேரம்",
  "c_Movement": "நடப்புமுறை",
  "c_Actions": "செயல்கள்",
  "c_Drawing": "வரைப்பு",
  "c_Events": "நிகழ்வுகள்",
  "c_Status": "நிலை",
  "c_Python": "பைதான்",
  "c_ExamplesMenu": "உதாரணங்கள் ...",
  "c_Examples": "உதுள்ளதாக",
  "c_Algorithms": "அல்கொரிதங்கள்",
  "t_saveTooltip": "கணினியில் நிரலை சேமிக்க",
  "t_readTooltip": "கணினியில் இருந்து நிரலை ஏற்றுக",
  "warn_entername": "மேல்தலைப்பின் வலது புலத்தில் Minecraft பயனர் பெயர் காணப்படவில்லை",
  "info_deploySuccess": "Minecraft-ல் %2 க்கான நிரல் தயார்",
  "info_deploySuccessWithWarning": "Minecraft-ல் நிரல் தயார் ஆனால் %2 ஆன்லைனில் இல்லை",
  "info_deployUnknownPlayer": "Mojang-க்கு %2 என்னும் பயனர் இல்லை",
  "infiniteLoopMessage": "முடிவற்ற மடல் கண்டறியப்பட்டதால் நிரல் நிறுத்தப்பட்டது"
}