var MSG = {
  "title": "โค้ด",
  "blocks": "บล็อก",
  "runTooltip": "เรียกใช้โปรแกรมที่กำหนดโดยบล็อกจากเวิร์กสเปซ",
  "timeout": "เกินจำนวนรอบการดำเนินการสูงสุดแล้ว",
  "trashTooltip": "ลบบล็อกทั้งหมด",
  "catLogic": "ตรรกะ",
  "catLoops": "ลูป",
  "catMath": "คณิตศาสตร์",
  "catText": "ข้อความ",
  "catLists": "รายการ",
  "catColour": "สี",
  "catVariables": "ตัวแปร",
  "catFunctions": "ฟังก์ชัน",
  "listVariable": "รายการ",
  "textVariable": "ข้อความ",
  "badXml": "ข้อผิดพลาดในการวิเคราะห์ XML:\n%1\n\nเลือก 'ตกลง' เพื่อยกเลิกการเปลี่ยนแปลงของคุณ หรือ 'ยกเลิก' เพื่อแก้ไข XML ต่อไป.",
  "c_Objects": "วัตถุ",
  "c_Blocks": "บล็อก",
  "c_Mobs": "ม็อบ",
  "c_Items": "ไอเทม",
  "c_Time": "เวลา",
  "c_Movement": "การเคลื่อนไหว",
  "c_Actions": "การกระทำ",
  "c_Drawing": "การวาดภาพ",
  "c_Events": "เหตุการณ์",
  "c_Status": "สถานะ",
  "c_Python": "Python",
  "c_ExamplesMenu": "ตัวอย่าง ...",
  "c_Examples": "ตัวอย่าง",
  "c_Algorithms": "อัลกอริทึม",
  "t_saveTooltip": "บันทึกโปรแกรมลงในคอมพิวเตอร์",
  "t_readTooltip": "โหลดโปรแกรมจากคอมพิวเตอร์",
  "warn_entername": "ชื่อผู้เล่น Minecraft หายไปในช่องด้านบนขวา",
  "info_deploySuccess": "โปรแกรมพร้อมใช้งานใน Minecraft สำหรับ %2",
  "info_deploySuccessWithWarning": "โปรแกรมพร้อมใช้งานใน Minecraft แต่ %2 ยังออนไลน์ไม่ได้",
  "info_deployUnknownPlayer": "Mojang ไม่มีผู้เล่นชื่อ %2",
  "infiniteLoopMessage": "โปรแกรมหยุดลงเนื่องจากตรวจพบลูปไม่สิ้นสุด"
}