var MSG = {
  "title": "Kodigo",
  "blocks": "Mga bloke",
  "runTooltip": "Patakbuhin ang program na tinukoy ng mga bloke sa workspace.",
  "timeout": "Nalampasan ang pinakamataas na bilang ng mga iterasyon ng pagpapatupad.",
  "trashTooltip": "Tanggalin ang lahat ng mga bloke.",
  "catLogic": "Lohika",
  "catLoops": "Mga loop",
  "catMath": "Matematika",
  "catText": "Teksto",
  "catLists": "Mga listahan",
  "catColour": "Kulay",
  "catVariables": "Mga variable",
  "catFunctions": "Mga function",
  "listVariable": "Listahan",
  "textVariable": "Teksto",
  "badXml": "Error sa pag-parse ng XML:\n%1\n\nPiliin ang 'OK' upang isuko ang iyong mga pagbabago o 'Cancel' upang higit pang i-edit ang XML.",
  
  "c_Objects": "Mga Bagay",
  "c_Blocks": "Mga bloke",
  "c_Mobs": "Nilalang",
  "c_Items": "Mga item",
  "c_Time": "Oras",
  "c_Movement": "Paggalaw",
  "c_Actions": "Mga aksyon",
  "c_Drawing": "Pagdodrowing",
  "c_Events": "Mga kaganapan",
  "c_Status": "Katayuan",
  "c_Python": "Python",
  "c_ExamplesMenu": "Mga Halimbawa ...",
  "c_Examples": "Mga Halimbawa",
  "c_Algorithms": "Mga Algorithm",
  "t_saveTooltip": "I-save ang program sa computer",
  "t_readTooltip": "I-load ang isang programa mula sa computer",
  "warn_entername": "Nawawala ang MINECRAFT PLAYER NAME sa kanang itaas na patlang",
  "info_deploySuccess": "Nakahanda na ang programa sa Minecraft para sa %2",
  "info_deploySuccessWithWarning": "Nakahanda na ang programa sa Minecraft pero hindi online ang %2",
  "info_deployUnknownPlayer": "Walang manlalaro na may pangalang %2 sa Mojang",
  "infiniteLoopMessage": "Tumigil ang programa dahil nadetect ang walang katapusang loop"
}