var MSG = {
  title: "Mã",
  blocks: "Khối",
  runTooltip: "Chạy chương trình được xác định bởi các khối trong không gian làm việc.",
  timeout: "Vượt quá số lần lặp thực thi tối đa.",
  trashTooltip: "Vứt bỏ tất cả các khối.",
  catLogic: "Logic",
  catLoops: "Vòng lặp",
  catMath: "Toán",
  catText: "Văn bản",
  catLists: "Danh sách",
  catColour: "Màu sắc",
  catVariables: "Biến",
  catFunctions: "Hàm",
  listVariable: "danh sách",
  textVariable: "văn bản",
  badXml: "Lỗi phân tích XML:\n%1\n\nChọn 'OK' để từ bỏ các thay đổi của bạn hoặc 'Cancel' để tiếp tục chỉnh sửa XML.",
  
  c_Objects : "Đối tượng",
  c_Blocks : "Khối",
  c_Mobs : "Sinh vật",
  c_Items : "Vật phẩm",
  c_Time : "Thời gian",
  c_Movement : "Di chuyển",
  c_Actions : "Hành động",
  c_Drawing : "Vẽ",
  c_Events : "Sự kiện",
  c_Status : "Trạng thái",
  c_Python : "Python",
  c_ExamplesMenu : "Ví dụ ...",
  c_Examples : "Ví dụ",
  c_Algorithms : "Thuật toán",
  t_saveTooltip : "Lưu chương trình vào máy tính",
  t_readTooltip : "Tải một chương trình từ máy tính",
  warn_entername :  "Tên người chơi Minecraft bị thiếu ở trường ở góc trên bên phải",
  info_deploySuccess :  "Chương trình đã sẵn sàng trong Minecraft cho %2",
  info_deploySuccessWithWarning :  "Chương trình đã sẵn sàng trong Minecraft nhưng %2 không trực tuyến",
  info_deployUnknownPlayer :  "Mojang không có người chơi có tên %2",
  infiniteLoopMessage : "Chương trình dừng lại vì phát hiện vòng lặp vô hạn"
};