var MSG = {
  "title": "代码",
  "blocks": "块",
  "runTooltip": "在工作区中由这些块定义的程序进行运行。",
  "timeout": "已超过最大执行迭代次数。",
  "trashTooltip": "丢弃所有块。",
  "catLogic": "逻辑",
  "catLoops": "循环",
  "catMath": "数学",
  "catText": "文本",
  "catLists": "列表",
  "catColour": "颜色",
  "catVariables": "变量",
  "catFunctions": "函数",
  "listVariable": "列表",
  "textVariable": "文本",
  "badXml": "解析 XML 时出错:\n%1\n\n选择\"确定\"以放弃你的修改，或\"取消\"以继续编辑 XML。",

  "c_Objects" : "对象",
  "c_Blocks" : "块",
  "c_Mobs" : "生物",
  "c_Items" : "物品",
  "c_Time" : "时间",
  "c_Movement" : "移动",
  "c_Actions" : "动作",
  "c_Drawing" : "绘画",
  "c_Events" : "事件",
  "c_Status" : "状态",
  "c_Python" : "Python",
  "c_ExamplesMenu" : "示例 ...",
  "c_Examples" : "示例",
  "c_Algorithms" : "算法",
  "t_saveTooltip" : "将程序保存到计算机。",
  "t_readTooltip" : "从计算机加载程序",
  "warn_entername" :  "右上角字段缺少 Minecraft 玩家名称",
  "info_deploySuccess" :  "程序已在 Minecraft 中就绪，供 %2 使用",
  "info_deploySuccessWithWarning" :  "程序已在 Minecraft 中就绪，但 %2 未在线",
  "info_deployUnknownPlayer" :  "Mojang 没有名为 %2 的玩家",
  "infiniteLoopMessage" : "检测到死循环，程序已停止"
}