/**
 * Define globals shared by the blocks definition, the generators and CodeMirror
 */

var Globals = {

  DIRECTION_DICTIONARY_LABEL  : "DIRECTION",
  DIRECTION_PYTHON_CLASSNAME  : "Direction",

  LEASH_DICTIONARY_LABEL  : "LEASH",
  LEASH_PYTHON_CLASSNAME  : "Leash",


  EQUIPMENT_PYTHON_CLASSNAME  : "Equip",

  COORDINATE_SYSTEM_PYTHON_CLASSNAME  : "Coordinate",

  COMPASS_PYTHON_CLASSNAME  : "Compass",


  TEAM_DICTIONARY_LABEL  : "TEAM",
  GROUND_DICTIONARY_LABEL  : "GROUND",
  BABY_DICTIONARY_LABEL  : "BABY",

  ENTITY_PYTHON_CLASSNAME  : "Entity.", 
  ITEM_PYTHON_CLASSNAME  : "Item.", 
  BLOCK_PYTHON_CLASSNAME  : "Block.",
 
  SIDE_DICTIONARY_LABEL  : "SIDE",
  SIDE_PYTHON_CLASSNAME  : "Side.", 

  DRAWINGSTARTPOSITION_PYTHON_CLASSNAME  : "Start.", 
  PARTICLE_PYTHON_CLASSNAME  : "Particle.", 
  BLOCK_NOTHING  : "Block.NOTHING",

  PLAYER_POSITION_PYTHON_CLASSNAME  : "Position." 
  };

